version: '3'

services:
  db:
    image: arm64v8/mysql:oracle
    container_name: sakila
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - sakila-data:/app

volumes:
  sakila-data:
